Crear una plantilla de issue para agregar contenido
siguealcongreso/sitioweb pull request #7
Opened 2023-09-03 18:32 UTC by ppaez

2023-09-03 19:09 UTC, Armandotrsg commented
Solo falta poner la template para las Pull Requests

2023-09-04 15:14 UTC, ppaez commented
Agregué la plantilla de Pull Request. Se usan comentarios para las sugerencias de qué escribir en cada apartado. La idea es que se borren al llenar los apartados, pero si se dejan no se muestran.

2023-09-04 15:29 UTC, Armandotrsg requested changes
En vez de usar `**` para las secciones de las templates, estaría mejor usar `#` o `##`respectivamente, que usar negritas tiene diferente valor semántico para separar contenido

2023-09-04 18:01 UTC, Armandotrsg approved these changes

2023-09-04 20:39 UTC, merged